-- Fix RLS for all tables
-- Run this in Supabase SQL Editor

ALTER TABLE IF EXISTS expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cleaning_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shopping_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bulletin_postits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bulletin_drawings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bulletin_text ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cleaning_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
